name: Deep Agent Automated Tests

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  test:
    runs-on: windows-latest  # Changed to Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        shell: pwsh
        run: |
          Write-Host "Installing dependencies..."
          npm install
          npm install -g playwright
          npx playwright install chromium
          New-Item -ItemType Directory -Force -Path .\test-results

      - name: Run Tests
        shell: pwsh
        env:
          NODE_OPTIONS: --experimental-vm-modules --no-warnings
          EXPORT_PATH: ${{ github.workspace }}\exports
          REPORT_PATH: ${{ github.workspace }}\reports
          TEST_RESULTS: ${{ github.workspace }}\test-results
        run: |
          npm run test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            reports/
            test-results/