name: Tests automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test tag to run (without @)'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps
        
    - name: Run all tests
      if: github.event.inputs.tags == ''
      run: npm run test
      env:
        CI: true
      
    - name: Run tests with specific tag
      if: github.event.inputs.tags != ''
      run: npm run test:tag "@${{ github.event.inputs.tags }}"
      env:
        CI: true
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ github.run_id }}
        path: |
          test-results/
          playwright-report/
          cucumber-report/
        retention-days: 30
        if-no-files-found: warn
        
    - name: Upload Playwright traces on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces-${{ github.run_id }}
        path: test-results/traces
        retention-days: 30
        if-no-files-found: ignore